# Generated by Django 6.0.4 on 2026-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='NGN', max_length=3),
        ),
    ]
